spring:
  application:
    name: test_task

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${DB_USERNAME:timurka228}
    password: ${DB_PASSWORD:timurka228}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  prefix: "/api/v1/"

server:
  port: ${SERVER_PORT:8088}